### ISSUE TITLE
AttributeError: 'float' object has no attribute 'min'

### ISSUE THREAD

**Issue by jmrichardson** [crowdcent/numerblox#171]
Hi,

Thank you for this great package!  Everything is working great so far except:

```
val['prediction'] = ag.predictor.predict(val)
val["example_preds"] = ExamplePredictions(f"v{version}/validation_example_preds.parquet", keep_files=False).fit_transform(None)['prediction']
evaluator = NumeraiClassicEvaluator()
metrics = evaluator.full_evaluation(val,
                                    pred_cols=["prediction"],
                                    target_col="target",
                                    benchmark_cols=["example_preds"])
```

Here is the error:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Projects\nai\pipelines\classic\ag_train_val.py", line 59, in <module>
    metrics = evaluator.full_evaluation(val,
  File "D:\Anaconda3\envs\mld\lib\site-packages\numerblox\evaluation.py", line 1009, in full_evaluation
    col_stats = self.evaluation_one_col(
  File "D:\Anaconda3\envs\mld\lib\site-packages\numerblox\evaluation.py", line 157, in evaluation_one_col
    dataf[pred_col].min().min() >= 0 and dataf[pred_col].max().max() <= 1
AttributeError: 'float' object has no attribute 'min'
```

numerblox 1.3.4

One too many min on pred column?

**Comment by CarloLepelaars** [comment]
Hey @jmrichardson, thanks for posting an issue about this! Which Python and Pandas versions are you using?

I just made these column checks more robust. Could you update to NumerBlox 1.3.5 (`pip install -U numerblox`) and check if this solves the issue?

Please let me know if you still encounter problems.

**Comment by jmrichardson** [comment]
Hi, 

Thank, it works now.  Appreciate the fast response:

Just a FYI, I did get the following after upgrade:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Anaconda3\envs\mld\lib\site-packages\numerblox\download.py", line 15, in <module>
    from numerapi import NumerAPI, SignalsAPI, CryptoAPI
ImportError: cannot import name 'CryptoAPI' from 'numerapi' (D:\Anaconda3\envs\mld\lib\site-packages\numerapi\__init__.py)
```

numerapi                               2.18.0
pandas                                   2.1.3
Python 3.10.13

Upgraded to numerapi 2.19.1, and no more issue. 

Thanks!

**Comment by CarloLepelaars** [comment]
Awesome, thanks for the heads up. Will make sure that the minimum version for numerapi is 2.19.1.
